version: '3.8'
services:
  application:
    build: 
      context: .
      dockerfile: Dockerfile
      target: development
    image: kslplus/application
    container_name: application
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    command: npm start
  storybook:
    build: 
      context: .
      dockerfile: Dockerfile
      target: development
    image: kslplus/storybook
    container_name: storybook
    volumes:
      - ./:/usr/src/app
    ports:
      - 6006:6006
    command: npm run storybook