version: '3.1'
services:
    rediscaching:
        container_name: rediscaching
        image: redis
        restart: always
        ports:
            - 6379:6379
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
            - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    mongodb:
        container_name: mongodb
        image: mongo
        restart: always
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME: root
            - MONGO_INITDB_ROOT_PASSWORD: 31Kp9T3Z!Hs+R=ma

    mysqldb:
        container_name: mysqldb
        image: mysql
        restart: always
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=vKq^1#*86zBp=5Z[
            - MYSQL_DATABASE=database
            - MYSQL_USER=user
            - MYSQL_PASSWORD=pa9^J#s9NOqmGv3C

    kafkabroker:
        container_name: kafkabroker
        image: apache/kafka:latest
        restart: always
        ports:
            - 9092:9092
        environment:
            - KAFKA_NODE_ID: 1
            - KAFKA_PROCESS_ROLES: broker,controller
            - KAFKA_LISTENERS: PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093
            - KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
            - KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
            - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
            - KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
            - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            - KAFKA_NUM_PARTITIONS: 3
